_commit: v1.6.5-3-g5fda948
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: certificates.yaml
backups: false
helm: true
helmCrds: false
helmName: nginx-ingress
helmRelease: nginx-external
helmRepo: https://helm.nginx.com/stable
helmValues: ''
helmVersion: 1.0.2
ingSecret: ''
ingress: false
labels: |-
  app.kubernetes.io/instance: external
  app.kubernetes.io/name: nginx-ingress
name: nginx-external
namespace: nginx-external
pvc: false
reloader: true
resources: []
service: false
serviceAccount: false
upstreamURL: https://nginx.org/en/
url: https://github.com/charlesthomas/homelab-nginx-external
