---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-external

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-nginx-external
commonLabels:
  app.kubernetes.io/instance: external
  app.kubernetes.io/name: nginx-ingress

resources:
- resources/certificates.yaml
- resources/namespaces.yaml
<<<<<<< before updating

=======
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: nginx-external
      namespace: nginx-external
      annotations:
        gethomepage.dev/href: https://nginx-external.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: nginx-external
        gethomepage.dev/name: nginx-external
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
>>>>>>> after updating
helmCharts:
- name: nginx-ingress
  namespace: nginx-external
  releaseName: nginx-external
  repo: https://helm.nginx.com/stable
  valuesFile: helm/values.yaml
  version: 1.0.2
