---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-external

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-nginx-external
commonLabels:
  app.kubernetes.io/instance: external
  app.kubernetes.io/name: nginx-ingress

resources:
- resources/certificates.yaml
- resources/namespaces.yaml

helmCharts:
- name: nginx-ingress
  namespace: nginx-external
  releaseName: nginx-external
  repo: https://helm.nginx.com/stable
  valuesFile: helm/values.yaml
  version: 1.0.2
